{{- if .Values.prometheus.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flink.fullname" . }}-jobmanager
  labels:
{{ include "flink.labels" . | indent 4 }}
{{ toYaml .Values.prometheus.serviceMonitor.selector | indent 4 }}
  namespace: {{ include "serviceMonitor.namespace" . }}
spec:
  endpoints:
    - interval: {{ .Values.prometheus.serviceMonitor.interval }}
      path: /
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  targetLabels:
    - app.kubernetes.io/name
    - component
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flink.name" . }}
      component: jobmanager

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flink.fullname" . }}-taskmanager
  labels:
{{ include "flink.labels" . | indent 4 }}
{{ toYaml .Values.prometheus.serviceMonitor.selector | indent 4 }}
  namespace: {{ include "serviceMonitor.namespace" . }}
spec:
  endpoints:
    - interval: {{ .Values.prometheus.serviceMonitor.interval }}
      path: /
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  targetLabels:
    - app.kubernetes.io/name
    - component
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flink.name" . }}
      component: taskmanager
{{- end }}
